services:
  - type: web
    name: linkguard-ml
    env: docker
    dockerContext: ./ml-service
    dockerfilePath: ./ml-service/Dockerfile
    plan: free
    region: ohio
    envVars:
      - key: LOG_LEVEL
        value: INFO
